version: "3.7"

services:
  host_app_dev:
    build:
      context: ./services/nginx/host-client
      dockerfile: Dockerfile.dev
    volumes:
      - ./services/nginx/host-client/:/usr/src/app/
      - ./services/nginx/host-client/node_modules/:/usr/src/app/node_modules
    ports:
      - 3001:3001
    env_file:
      - ./.env.dev
    stdin_open: true

  guest_app_dev:
    build:
      context: ./services/nginx/jukebox-client
      dockerfile: Dockerfile.dev
    volumes:
      - ./services/nginx/jukebox-client/:/usr/src/app/
      - ./services/nginx/jukebox-client/node_modules/:/usr/src/app/node_modules
    ports:
      - 3000:3000
    env_file:
      - ./.env.dev
    stdin_open: true

  nginx:
    build:
      context: ./services/nginx
      dockerfile: Dockerfile.dev
    volumes:
      - ./services/nginx/jukebox-client/:/usr/src/app/
    ports:
      - 80:80
    depends_on:
      - player
      - room_settings
      - spotify_login_handler
      - typeahead

  room_settings:
    build: ./services/room_settings
    volumes:
      - ./services/room_settings/:/usr/src/app/
    ports:
      - 5000:5000
    env_file:
      - ./.env.dev
    depends_on:
      - redis
      - rabbitmq

  spotify_login_handler:
    build: ./services/spotify_login_handler
    volumes:
      - ./services/spotify_login_handler/:/usr/src/app/
    ports:
      - 5003:5003
    env_file:
      - ./.env.dev
    depends_on:
      - redis
      - rabbitmq

  player:
    build: ./services/player
    volumes:
      - ./services/player/:/usr/src/app/
    ports:
      - 5002:5002
    env_file:
      - ./.env.dev
    depends_on:
      - redis

  typeahead:
    build: ./services/typeahead
    volumes:
      - ./services/typeahead/:/usr/src/app/
    ports:
      - 5001:5001
    env_file:
      - ./.env.dev
    depends_on:
      - redis

  make_authorized_request:
    build: ./services/authorizer/workers/make_authorized_request
    volumes:
      - ./services/authorizer/workers/make_authorized_request/:/usr/src/app/
    env_file:
      - ./.env.dev
    depends_on:
      - redis
      - rabbitmq

  create_authorization:
    build: ./services/authorizer/workers/create_authorization
    volumes:
      - ./services/authorizer/workers/create_authorization/:/usr/src/app/
    env_file:
      - ./.env.dev
    depends_on:
      - redis
      - rabbitmq
      - postgres

  refresh_authorization:
    build: ./services/authorizer/workers/refresh_authorization
    volumes:
      - ./services/authorizer/workers/refresh_authorization/:/usr/src/app/
    env_file:
      - ./.env.dev
    depends_on:
      - redis
      - rabbitmq
      - postgres

  create_or_update_user:
    build: ./services/user/workers/create_or_update_user
    volumes:
      - ./services/user/workers/create_or_update_user/:/usr/src/app/
    depends_on:
      - rabbitmq
      - postgres
    env_file:
      - ./.env.dev

  redis:
    image: redis:6
    ports:
      - 6379:6379

  rabbitmq:
    hostname: rabbitmq
    image: rabbitmq:3-management
    ports:
      - 15672:15672

  postgres:
    image: postgres:12
    env_file:
      - ./.env.dev
    volumes:
      - postgres-data:/var/lib/postgresql/data/

  pgmanager:
    build: ./services/postgres
    volumes:
      - ./services/postgres/:/usr/src/app/
    env_file:
      - ./.env.dev
    depends_on:
      - postgres

volumes:
  postgres-data:
