version: "3.7"

services:
  room_settings:
    build: ./services/room_settings
    volumes:
      - ./services/room_settings/:/usr/src/app/
    ports:
      - 5000:5000
    env_file:
      - ./services/room_settings/.env.dev
    depends_on:
      - redis
      - rabbitmq

  typeahead:
    build: ./services/typeahead
    volumes:
      - ./services/typeahead/:/usr/src/app/
    ports:
      - 5001:5001
    env_file:
      - ./services/typeahead/.env.dev
    depends_on:
      - redis

  player:
    build: ./services/player
    volumes:
      - ./services/player/:/usr/src/app/
    ports:
      - 5002:5002
    env_file:
      - ./services/player/.env.dev
    depends_on:
      - redis

  make_authorized_request:
    build: ./services/authorizer/workers/make_authorized_request
    volumes:
      - ./services/authorizer/workers/make_authorized_request/:/usr/src/app/
    env_file:
      - ./services/authorizer/workers/.env.dev
    depends_on:
      - redis
      - rabbitmq
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

  create_authorization:
    build: ./services/authorizer/workers/create_authorization
    volumes:
      - ./services/authorizer/workers/create_authorization/:/usr/src/app/
    env_file:
      - ./services/authorizer/workers/.env.dev
    depends_on:
      - redis
      - rabbitmq
      - postgres
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

  refresh_authorization:
    build: ./services/authorizer/workers/refresh_authorization
    volumes:
      - ./services/authorizer/workers/refresh_authorization/:/usr/src/app/
    env_file:
      - ./services/authorizer/workers/.env.dev
    depends_on:
      - redis
      - rabbitmq
      - postgres
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

  create_or_update_user:
    build: ./services/user/workers/create_or_update_user
    volumes:
      - ./services/user/workers/create_or_update_user/:/usr/src/app/
    depends_on:
      - rabbitmq
      - postgres
    env_file:
      - ./services/user/workers/.env.dev

  redis:
    image: redis:6

  rabbitmq:
    hostname: rabbitmq
    image: rabbitmq:3-management
    ports:
      - 15672:15672
      - 5672:5672

  postgres:
    image: postgres:12
    env_file:
      - ./services/postgres/.env.dev
    volumes:
      - postgres-data:/var/lib/postgresql/data/

  pgmanager:
    build: ./services/postgres
    volumes:
      - ./services/postgres/:/usr/src/app/
    env_file:
      - ./services/postgres/.env.dev
    depends_on:
      - postgres

volumes:
  postgres-data:
