version: "3.7"

services:
  nginx:
    build: ./services/nginx
    volumes:
      - ./services/nginx/guest-app/:/usr/src/app/
    ports:
      - 80:80
    env_file:
      - ./services/room_settings/.env.prod
    depends_on:
      - room_settings
      - typeahead
      - player

  room_settings:
    build: ./services/room_settings
    command: gunicorn --bind 0.0.0.0:5000 app:app
    env_file:
      - ./services/room_settings/.env.prod
    depends_on:
      - redis
      - rabbitmq

  player:
    build: ./services/player
    command: gunicorn --bind 0.0.0.0:5002 app:app
    env_file:
      - ./services/player/.env.prod
    depends_on:
      - redis

  typeahead:
    build: ./services/typeahead
    command: gunicorn --bind 0.0.0.0:5001 app:app
    env_file:
      - ./services/typeahead/.env.prod
    depends_on:
      - redis

  make_authorized_request:
    build: ./services/authorizer/workers/make_authorized_request
    env_file:
      - ./services/authorizer/workers/.env.prod
    depends_on:
      - redis
      - rabbitmq

  create_authorization:
    build: ./services/authorizer/workers/create_authorization
    env_file:
      - ./services/authorizer/workers/.env.prod
    depends_on:
      - redis
      - rabbitmq
      - postgres

  refresh_authorization:
    build: ./services/authorizer/workers/refresh_authorization
    env_file:
      - ./services/authorizer/workers/.env.prod
    depends_on:
      - redis
      - rabbitmq
      - postgres

  redis:
    image: redis:6

  rabbitmq:
    hostname: rabbitmq
    image: rabbitmq:3-management
    ports:
      - 15672:15672

  postgres:
    image: postgres:12
    env_file:
      - ./services/postgres/.env.prod
    volumes:
      - postgres-data:/var/lib/postgresql/data/

  pgmanager:
    build: ./services/postgres
    env_file:
      - ./services/postgres/.env.prod
    depends_on:
      - postgres

volumes:
  postgres-data:
