FROM node:latest as build-stage
WORKDIR /usr/src/app
COPY ./jukebox-client/package*.json ./

RUN npm install
COPY ./jukebox-client .
RUN npm run build

FROM nginx as production-stage
RUN mkdir /app
COPY --from=build-stage /usr/src/app/dist /app
COPY nginx.prod.conf /etc/nginx/nginx.conf