FROM node:latest

# This is a little strange. In production nginx serves this app, but in
# development it has its own container.

WORKDIR /usr/src/app
COPY ./package*.json ./

RUN npm install
COPY . .

EXPOSE 3001

CMD ["npm", "run", "start"]